### ISSUE TITLE
[FEAT] 상품 예약 등록 기능

### ISSUE THREAD

**Issue by SuHyeonEo** [eosugod/TradeHub#10]
## 💡 Feature Issue

구매자가 구매하고 싶은 상품에 예약 신청을 할 수 있다.
## 🌿  To-do

- [ ] 구매자가 특정 상품에 예약 신청을 하면, 판매자는 이를 수락할 수 있다.
- [ ] 상품 예약 시, 구매자의 보유 잔액(cash)이 상품 가격과 같거나 많아야 한다.
- [ ] 예약이 확정되면 구매자의 포인트가 상품의 가격만큼 차감 된다.
- [ ] 예약을 통해서 거래 장소, 일자를 확정할 수 있다.
