### ISSUE TITLE
[FEAT] 상품 예약 확정 기능

### ISSUE THREAD

**Issue by SuHyeonEo** [eosugod/TradeHub#15]
## 💡 Feature Issue

판매자는 판매 상품에 걸린 예약 중 하나를 확정 시킬 수 있다.
## 🌿  To-do

- [ ] 예약이 확정되면 상품의 상태가 판매중 -> 예약중으로 변경된다.
- [ ] 이미 확정된 예약이 있는 상품이라면, 다른 예약을 확정할 수 없다.
- [ ] 기존의 예약을 취소하고 다른 예약을 확정할 수 있다.
